# Generated by Django 2.1 on 2018-09-28 01:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Task list',
                'verbose_name_plural': 'Task lists',
            },
        ),
        migrations.CreateModel(
            name='TodosGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='todos',
            name='todos_group',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='todos.TodosGroup'),
        ),
    ]
