# Generated by Django 2.1 on 2018-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(choices=[('American', 'American'), ('American plus', 'American plus'), ('American petite', 'American petite'), ('Avenue American Plus', 'Avenue American Plus'), ('Asian', 'Asian'), ('NA', 'NA')], max_length=30)),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='spec',
            field=models.OneToOneField(default=1, on_delete='CASCADE', to='inventory.spec'),
            preserve_default=False,
        ),
    ]
