# Generated by Django 2.1 on 2018-09-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180918_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='spec',
        ),
        migrations.AddField(
            model_name='inventory',
            name='spec',
            field=models.ManyToManyField(to='inventory.spec'),
        ),
    ]
