# Generated by Django 2.1 on 2018-09-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180918_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='spec',
            field=models.ManyToManyField(to='inventory.Spec'),
        ),
    ]
