# Generated by Django 2.1 on 2018-08-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleApprovalByBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Create On')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('ndue_date_note', models.CharField(blank=True, max_length=100)),
                ('factory_TA', models.DateField(blank=True, null=True)),
                ('nfactory_ta', models.CharField(blank=True, max_length=100)),
                ('date_sent_to_jp', models.DateField(blank=True, null=True)),
                ('ndate_sent_to_jp', models.CharField(blank=True, max_length=100)),
                ('buyer_approval_date', models.DateField(blank=True, null=True)),
                ('buyer_approval_status', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('In progress', 'in_progress'), ('Completed', 'completed'), ('Cancelled', 'cancelled')], max_length=20)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, on_delete='CASCADE', to='orders.Orders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='sampleapprovalbybuyer',
            name='type',
            field=models.ForeignKey(on_delete='CASCADE', to='task.TaskType'),
        ),
    ]
