# Generated by Django 2.1 on 2018-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTaskBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Create On')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_note', models.CharField(blank=True, max_length=100)),
                ('factory_ta', models.DateField(blank=True, null=True)),
                ('factory_ta_note', models.CharField(blank=True, max_length=100)),
                ('date_sent_to_jp', models.DateField(blank=True, null=True)),
                ('date_sent_to_jp_note', models.CharField(blank=True, max_length=100)),
                ('buyer_approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In progress', 'in_progress'), ('Completed', 'completed'), ('Cancelled', 'cancelled')], max_length=20)),
                ('standard_task_note', models.TextField(blank=True, null=True, verbose_name='General Notes')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, on_delete='CASCADE', to='orders.Orders')),
                ('type', models.ForeignKey(on_delete='CASCADE', to='task.TaskType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sampleapprovalbybuyer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sampleapprovalbybuyer',
            name='type',
        ),
        migrations.DeleteModel(
            name='SampleApprovalByBuyer',
        ),
    ]
