# Generated by Django 2.1 on 2018-09-18 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'task_due_date': '', 'task_name': '', 'task_note': ''}),
        ),
    ]
