# Generated by Django 2.1 on 2018-09-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('task', '0004_task_task_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostcoSampleTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Create On')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_factory_ta', models.DateField(blank=True, null=True)),
                ('jp_approval_sent_to_buyer', models.DateField(blank=True, null=True)),
                ('buyer_approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In progress', 'in_progress'), ('Completed', 'completed'), ('Cancelled', 'cancelled')], max_length=20)),
                ('standard_task_note', models.TextField(blank=True, null=True, verbose_name='General Notes')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='sampletaskbasic',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sampletaskbasic',
            name='type',
        ),
        migrations.DeleteModel(
            name='SampleTaskBasic',
        ),
        migrations.AddField(
            model_name='costcosampletasks',
            name='name',
            field=models.OneToOneField(on_delete='CASCADE', to='task.TaskName'),
        ),
        migrations.AddField(
            model_name='costcosampletasks',
            name='order',
            field=models.ForeignKey(blank=True, on_delete='CASCADE', to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='costcosampletasks',
            name='type',
            field=models.ForeignKey(on_delete='CASCADE', to='task.TaskType'),
        ),
    ]
