# Generated by Django 2.1 on 2018-09-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_order_number', models.CharField(blank=True, max_length=100, verbose_name='Buyer Order Number')),
                ('buyer_style_number', models.CharField(blank=True, max_length=100, verbose_name='Buyer Style Number')),
                ('jp_style_number', models.CharField(blank=True, max_length=20, verbose_name='Jeanne Pierre Style Number')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('factory_ship_date', models.DateField(blank=True, null=True, verbose_name='Ship to Factory Date')),
                ('cost_from_factory', models.FloatField(blank=True, verbose_name='Factory Cost')),
                ('buyers_price', models.FloatField(blank=True, verbose_name='Price Buyer Paid')),
                ('order_type', models.CharField(choices=[('DDP', 'DDP'), ('FOB', 'FOB'), ('NA', 'NA')], max_length=40, null=True, verbose_name='Shipment Type')),
                ('qty', models.FloatField(blank=True, verbose_name='Order Qty')),
                ('sweater_image', models.ImageField(blank=True, upload_to='sweater_images/', verbose_name='Item Image')),
                ('sweater_description', models.TextField(blank=True, max_length=200, verbose_name='Item Des.')),
                ('brand', models.CharField(blank=True, choices=[('888', 'eight eight eight'), ('JP', 'JEANNE PIERRE'), ('AVE', 'AVENUE'), ('OTHER', 'PRIVATE LABEL')], max_length=40, verbose_name='Label')),
                ('fiber_content', models.TextField(blank=True, max_length=200, verbose_name='Fiber Content Des.')),
                ('jp_care_instructions', models.TextField(blank=True, max_length=250, verbose_name='Care Instructions - before translation')),
                ('color', models.CharField(blank=True, max_length=75, verbose_name='Color Des.')),
                ('buyer', models.ForeignKey(blank=True, on_delete='Buyer', to='customer.Customer', verbose_name='Buyer')),
                ('factory', models.ForeignKey(blank=True, max_length=100, on_delete='Factory', to='factory.Factory', verbose_name='Factory')),
            ],
        ),
    ]
