# Generated by Django 2.1 on 2018-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('DDP', 'Delivary Duty Paid'), ('FOB', 'Freight On Board'), ('NA', 'NA')], max_length=40, null=True, verbose_name='Shipment Type'),
        ),
    ]
