# Generated by Django 2.1 on 2018-09-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180918_2019'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='jp_style_number_test',
            field=models.ForeignKey(blank=True, default=1, on_delete='Jp Style Number', to='inventory.Inventory', verbose_name='Jp Style'),
            preserve_default=False,
        ),
    ]
