# Generated by Django 2.1 on 2018-09-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180918_2023'),
        ('orders', '0002_orders_jp_style_number_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='jp_style_number_test',
        ),
        migrations.AddField(
            model_name='orders',
            name='jp_style_number_test',
            field=models.ManyToManyField(blank=True, related_name='_orders_jp_style_number_test_+', to='inventory.Inventory', verbose_name='Jp Style'),
        ),
    ]
