# Generated by Django 2.1 on 2018-09-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180905_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('DDP', 'DDP'), ('FOB', 'FOB'), ('NA', 'NA')], max_length=40, null=True, verbose_name='Shipment Type'),
        ),
    ]
